import { expandServices } from "./service-names.ts";
import type { OnboardState } from "./types.ts";

// Docker Compose env var references use ${VAR} syntax which triggers biome's
// noTemplateCurlyInString rule. We collect them via a helper to keep the
// suppression comments in one place.

// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_API_KEY = "      - API_KEY=${API_KEY}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_SLACK_BOT_TOKEN = "      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_SLACK_APP_TOKEN = "      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_CLAUDE_OAUTH = "      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_ANTHROPIC_KEY = "      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_GITHUB_TOKEN = "      - GITHUB_TOKEN=${GITHUB_TOKEN}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_GITHUB_EMAIL = "      - GITHUB_EMAIL=${GITHUB_EMAIL}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_GITHUB_NAME = "      - GITHUB_NAME=${GITHUB_NAME}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_GITLAB_TOKEN = "      - GITLAB_TOKEN=${GITLAB_TOKEN}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_GITLAB_EMAIL = "      - GITLAB_EMAIL=${GITLAB_EMAIL}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_SENTRY_AUTH_TOKEN = "      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}";
// biome-ignore lint/suspicious/noTemplateCurlyInString: Docker Compose env var syntax
const ENV_SENTRY_ORG = "      - SENTRY_ORG=${SENTRY_ORG}";

/**
 * Generate a docker-compose.yml string from onboard wizard state.
 * Builds the YAML as plain strings (no YAML library) following the pattern
 * used in templates-ui/src/lib/compose-generator.ts.
 */
export function generateCompose(state: OnboardState): string {
  const expanded = expandServices(state.services, state.agentIds);
  const lines: string[] = [];

  // Header
  lines.push("# Docker Compose for Agent Swarm");
  lines.push("# Generated by `agent-swarm onboard`");
  lines.push("#");
  lines.push("# Usage:");
  lines.push("#   docker compose --env-file .env up -d");
  lines.push("");
  lines.push("services:");

  // ── API service ──
  lines.push("  swarm-api:");
  lines.push('    image: "ghcr.io/desplega-ai/agent-swarm:latest"');
  lines.push("    container_name: swarm-api");
  lines.push("    pull_policy: always");
  lines.push("    stop_grace_period: 60s");
  lines.push("");
  const port = state.apiPort || 3013;

  lines.push("    environment:");
  lines.push(ENV_API_KEY);
  lines.push(`      - MCP_BASE_URL=http://localhost:${port}`);
  lines.push("      - APP_URL=https://app.agent-swarm.dev");

  if (state.integrations.slack) {
    lines.push("      - SLACK_DISABLE=false");
    lines.push(ENV_SLACK_BOT_TOKEN);
    lines.push(ENV_SLACK_APP_TOKEN);
  }

  if (state.integrations.github) {
    lines.push("      - GITHUB_DISABLE=false");
  }

  lines.push("");
  lines.push("    ports:");
  lines.push(`      - "${port}:3013"`);
  lines.push("");
  lines.push("    volumes:");
  lines.push("      - swarm_data:/app/data");
  lines.push("");
  lines.push("    healthcheck:");
  lines.push('      test: ["CMD-SHELL", "curl -f http://localhost:3013/health || exit 1"]');
  lines.push("      interval: 10s");
  lines.push("      timeout: 5s");
  lines.push("      retries: 3");
  lines.push("      start_period: 15s");
  lines.push("");
  lines.push("    restart: unless-stopped");

  // ── Agent services ──
  let nextPort = 3201;

  for (const svc of expanded) {
    const port = nextPort++;
    const agentRole = svc.entry.isLead ? "lead" : "worker";
    const agentName =
      svc.entry.count > 1 ? `${svc.entry.displayName} ${svc.index + 1}` : svc.entry.displayName;

    lines.push("");
    lines.push(`  ${svc.name}:`);
    lines.push('    image: "ghcr.io/desplega-ai/agent-swarm-worker:latest"');
    lines.push(`    container_name: ${svc.containerName}`);
    lines.push("    pull_policy: always");
    lines.push("    stop_grace_period: 60s");
    lines.push("");
    lines.push("    depends_on:");
    lines.push("      swarm-api:");
    lines.push("        condition: service_healthy");
    lines.push("");
    lines.push("    environment:");
    if (state.credentialType === "api_key") {
      lines.push(ENV_ANTHROPIC_KEY);
    } else {
      lines.push(ENV_CLAUDE_OAUTH);
    }
    lines.push(ENV_API_KEY);
    lines.push(`      - AGENT_ID=${svc.agentId}`);
    lines.push(`      - AGENT_NAME=${agentName}`);
    lines.push(`      - AGENT_ROLE=${agentRole}`);
    lines.push(`      - TEMPLATE_ID=${svc.entry.template}`);
    lines.push("      - MCP_BASE_URL=http://swarm-api:3013");
    lines.push("      - YOLO=true");
    lines.push("      - SWARM_URL=http://swarm-api:3013");

    if (svc.entry.isLead) {
      lines.push("      - MAX_CONCURRENT_TASKS=1");
    }

    if (state.integrations.github) {
      lines.push(ENV_GITHUB_TOKEN);
      lines.push(ENV_GITHUB_EMAIL);
      lines.push(ENV_GITHUB_NAME);
    }

    if (state.integrations.gitlab) {
      lines.push(ENV_GITLAB_TOKEN);
      lines.push(ENV_GITLAB_EMAIL);
    }

    if (state.integrations.sentry) {
      lines.push(ENV_SENTRY_AUTH_TOKEN);
      lines.push(ENV_SENTRY_ORG);
    }

    lines.push("");
    lines.push("    ports:");
    lines.push(`      - "${port}:3000"`);
    lines.push("");
    lines.push("    volumes:");
    lines.push("      - swarm_logs:/app/logs");
    lines.push("      - swarm_shared:/app/shared");
    lines.push(`      - swarm_${svc.sanitizedName}:/app/agent`);
    lines.push("");
    lines.push("    restart: unless-stopped");
  }

  // ── Volumes section ──
  lines.push("");
  lines.push("volumes:");
  lines.push("  swarm_data:");
  lines.push("  swarm_logs:");
  lines.push("  swarm_shared:");
  for (const svc of expanded) {
    lines.push(`  swarm_${svc.sanitizedName}:`);
  }

  return `${lines.join("\n")}\n`;
}
