/**
 * Generates API reference pages from the OpenAPI spec, grouped by tag.
 * Run: bun scripts/generate-docs.ts
 *
 * Reads ../openapi.json and creates:
 * - content/docs/api-reference/index.mdx (overview with version)
 * - content/docs/api-reference/<tag>.mdx (one per tag group)
 * - content/docs/api-reference/meta.json (auto-generated sidebar)
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const specPath = resolve(__dirname, "../../openapi.json");
const outputDir = resolve(__dirname, "../content/docs/api-reference");

const spec = JSON.parse(readFileSync(specPath, "utf-8"));

const version: string = spec.info?.version ?? "unknown";
const serverUrl: string = spec.servers?.[0]?.url ?? "http://localhost:3013";

// --- Group operations by tag ---

interface Operation {
  path: string;
  method: string;
  summary: string;
}

const tagGroups = new Map<string, Operation[]>();

for (const [path, methods] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(methods as Record<string, unknown>)) {
    if (typeof op !== "object" || op === null) continue;
    const opObj = op as { tags?: string[]; summary?: string };
    const tags = opObj.tags?.length ? opObj.tags : ["Other"];
    for (const tag of tags) {
      if (!tagGroups.has(tag)) tagGroups.set(tag, []);
      tagGroups.get(tag)!.push({
        path,
        method,
        summary: opObj.summary ?? "",
      });
    }
  }
}

// Sort tags alphabetically, sort operations within each tag
const sortedTags = [...tagGroups.keys()].sort();
for (const tag of sortedTags) {
  tagGroups
    .get(tag)!
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

// --- Slug helper ---

function slugify(tag: string): string {
  return tag
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// --- Clean output directory (remove old generated .mdx files) ---

mkdirSync(outputDir, { recursive: true });

if (existsSync(outputDir)) {
  for (const file of readdirSync(outputDir)) {
    if (file.endsWith(".mdx")) {
      rmSync(resolve(outputDir, file));
    }
  }
}

// --- Generate index page ---

const totalOps = [...tagGroups.values()].reduce((sum, ops) => sum + ops.length, 0);

const tagList = sortedTags
  .map((tag) => {
    const slug = slugify(tag);
    const count = tagGroups.get(tag)!.length;
    return `- [${tag}](/docs/api-reference/${slug}) — ${count} endpoint${count !== 1 ? "s" : ""}`;
  })
  .join("\n");

const indexMdx = `---
title: API Reference
description: Complete REST API reference for Agent Swarm — 171 endpoints across tasks, agents, workflows, memory, webhooks, and more. Build multi-agent orchestration with HTTP APIs and real-time event streaming.
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

## Agent Swarm API v${version}

Base URL: \`${serverUrl}\`

${totalOps} endpoints across ${sortedTags.length} categories.

### Categories

${tagList}
`;

writeFileSync(resolve(outputDir, "index.mdx"), indexMdx);

// --- Tag descriptions for SEO (used in frontmatter) ---

const tagDescriptions: Record<string, string> = {
  "API Keys": "Manage API keys for authenticating requests to the Agent Swarm API",
  "Active Sessions": "Monitor and control active agent sessions running in the swarm",
  "Agents": "CRUD operations for agent profiles — create, configure, update, and manage swarm agents",
  "ApprovalRequests": "Human-in-the-loop approval requests — review and respond to agent-escalated decisions",
  "Budgets": "Configure per-agent and global daily cost budgets to control AI agent spend",
  "Config": "Read and write swarm configuration values — global, agent-scoped, and repo-scoped settings",
  "Debug": "Debug utilities for inspecting swarm state and diagnosing agent issues",
  "Ecosystem": "Query registered community and official agent integrations in the swarm ecosystem",
  "Events": "Stream and query swarm lifecycle events — task transitions, agent state changes, and audit log",
  "Heartbeat": "Health check endpoint — verify the Agent Swarm API is running and reachable",
  "Integrations": "Configure third-party integrations — Slack, GitHub, GitLab, Linear, Jira, Sentry, and more",
  "MCP OAuth": "OAuth flows for MCP client authorization — register and manage OAuth connections",
  "MCP Servers": "Register and manage MCP tool servers available to swarm agents",
  "Memory": "Search, retrieve, and manage persistent agent memories across sessions",
  "Poll": "Long-poll endpoints for real-time task and message notifications without WebSockets",
  "Pricing": "Retrieve model pricing data used for cost tracking and budget enforcement across agents",
  "PromptTemplates": "Store and retrieve reusable prompt templates for consistent agent instructions",
  "Repos": "Register code repositories and configure VCS integration for automated task triggers",
  "Schedules": "Create and manage scheduled tasks — run agents on cron expressions or one-time delays",
  "Session Data": "Access session-level data including token counts, costs, and context window metrics",
  "Skills": "Install, publish, and manage skills — reusable agent behaviors and tool sets",
  "Stats": "Aggregate statistics for swarm activity — task counts, agent utilization, and cost summaries",
  "Tasks": "Core task API — create, assign, update, and monitor tasks across the swarm",
  "Trackers": "Integrate with Linear and Jira ticket trackers — sync issues to swarm tasks bidirectionally",
  "Webhooks": "Register and manage webhooks for real-time swarm event delivery to external systems",
  "WorkflowEvents": "Subscribe to and manage workflow lifecycle events — run status, step completions, failures, and convergence gates for DAG orchestration",
  "Workflows": "Define and execute DAG-based multi-step workflows with branching, triggers, and agent task nodes",
};

// --- Generate per-tag pages ---

for (const tag of sortedTags) {
  const slug = slugify(tag);
  const ops = tagGroups.get(tag)!;
  const opsJson = JSON.stringify(ops.map((o) => ({ path: o.path, method: o.method })));
  const description = tagDescriptions[tag] ?? `${tag} API endpoints`;

  const tagMdx = `---
title: "${tag}"
description: "${description}"
full: true
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

<APIPage document={"../openapi.json"} operations={${opsJson}} />
`;


  writeFileSync(resolve(outputDir, `${slug}.mdx`), tagMdx);
}

// --- Generate meta.json ---

const pages = ["index", ...sortedTags.map(slugify)];

const metaJson = {
  title: `API Reference v${version}`,
  description: "REST API reference for Agent Swarm",
  root: true,
  pages,
};

writeFileSync(resolve(outputDir, "meta.json"), `${JSON.stringify(metaJson, null, 2)}\n`);

console.log(
  `Generated API reference: ${sortedTags.length} tag pages + index (${totalOps} operations, v${version})`,
);
