#!/bin/bash
# Serve a static HTML report as an artifact
ARTIFACT_DIR="/workspace/personal/artifacts/my-report"
mkdir -p "$ARTIFACT_DIR"

cat > "$ARTIFACT_DIR/index.html" << 'HTML'
<!DOCTYPE html>
<html>
<head><title>Agent Report</title></head>
<body>
  <h1>Analysis Report</h1>
  <p>Generated by agent</p>
</body>
</html>
HTML

artifact serve "$ARTIFACT_DIR" --name "my-report"
