export interface ServiceEntry {
  template: string; // e.g. "official/lead"
  displayName: string;
  count: number;
  role: string;
  isLead?: boolean;
}

export interface ComposeConfig {
  services: ServiceEntry[];
  apiImage: string;
  workerImage: string;
  startingPort: number;
  integrations: {
    slack: boolean;
    github: boolean;
    gitlab: boolean;
    sentry: boolean;
  };
}

interface GeneratedService {
  name: string;
  agentId: string;
  agentName: string;
  agentRole: string;
  templateId: string;
  port: number;
  volumeName: string;
  isLead: boolean;
}

let uuidCounter = 0;

function generateUUID(): string {
  // Use a deterministic counter-based UUID to avoid SSR/client hydration mismatch.
  // Users should replace these with real UUIDs in their .env.
  uuidCounter++;
  const hex = uuidCounter.toString(16).padStart(12, "0");
  return `00000000-0000-4000-8000-${hex}`;
}

export function resetUUIDCounter() {
  uuidCounter = 0;
}

function buildServices(config: ComposeConfig): GeneratedService[] {
  const services: GeneratedService[] = [];
  let portOffset = 0;

  for (const entry of config.services) {
    for (let i = 0; i < entry.count; i++) {
      const suffix = entry.count > 1 ? `-${i + 1}` : "";
      const baseName = entry.isLead ? "lead" : `worker-${entry.role}`;
      const name = `${baseName}${suffix}`;
      const volumeSuffix = name.replace(/-/g, "_");

      services.push({
        name,
        agentId: generateUUID(),
        agentName: entry.displayName + (entry.count > 1 ? ` ${i + 1}` : ""),
        agentRole: entry.isLead ? "lead" : "worker",
        templateId: entry.template,
        port: config.startingPort + portOffset,
        volumeName: `swarm_${volumeSuffix}`,
        isLead: !!entry.isLead,
      });
      portOffset++;
    }
  }

  return services;
}

export function generateCompose(config: ComposeConfig): string {
  resetUUIDCounter();
  const services = buildServices(config);
  const lines: string[] = [];

  lines.push("# Docker Compose for Agent Swarm");
  lines.push("# Generated by Agent Swarm Templates Builder");
  lines.push("#");
  lines.push("# Usage:");
  lines.push("#   docker-compose --env-file .env up -d");
  lines.push("");
  lines.push("services:");

  // API service
  lines.push("  api:");
  lines.push(`    image: "${config.apiImage}"`);
  lines.push("    pull_policy: always");
  lines.push("    stop_grace_period: 60s");
  lines.push("");
  lines.push("    environment:");
  lines.push("      - API_KEY=${API_KEY}");
  lines.push("      - MCP_BASE_URL=${MCP_BASE_URL}");
  lines.push("      - APP_URL=${APP_URL}");

  if (config.integrations.slack) {
    lines.push("      - SLACK_DISABLE=${SLACK_DISABLE:-false}");
    lines.push("      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}");
    lines.push("      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-}");
  }

  lines.push("");
  lines.push("    ports:");
  lines.push('      - "3013:3013"');
  lines.push("");
  lines.push("    volumes:");
  lines.push("      - swarm_api:/app");
  lines.push("");
  lines.push("    healthcheck:");
  lines.push('      test: ["CMD-SHELL", "curl -f http://localhost:3013/health || exit 1"]');
  lines.push("      interval: 30s");
  lines.push("      timeout: 10s");
  lines.push("      retries: 3");
  lines.push("      start_period: 40s");
  lines.push("");
  lines.push("    restart: unless-stopped");

  // Agent services
  for (const svc of services) {
    lines.push("");
    lines.push(`  ${svc.name}:`);
    lines.push(`    image: "${config.workerImage}"`);
    lines.push("    pull_policy: always");
    lines.push("    stop_grace_period: 60s");
    lines.push("");
    lines.push("    depends_on:");
    lines.push("      api:");
    lines.push("        condition: service_healthy");
    lines.push("");
    lines.push("    environment:");
    lines.push("      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}");
    lines.push("      - API_KEY=${API_KEY}");
    lines.push(`      - AGENT_ID=${svc.agentId}`);
    lines.push(`      - AGENT_NAME=${svc.agentName}`);
    lines.push(`      - AGENT_ROLE=${svc.agentRole}`);
    lines.push(`      - TEMPLATE_ID=${svc.templateId}`);
    lines.push("      - MCP_BASE_URL=http://api:3013");
    lines.push("      - YOLO=true");
    lines.push("      - SWARM_URL=${SWARM_URL:-localhost}");

    if (config.integrations.github) {
      lines.push("      - GITHUB_TOKEN=${GITHUB_TOKEN:-}");
      lines.push("      - GITHUB_EMAIL=${GITHUB_EMAIL:-}");
      lines.push("      - GITHUB_NAME=${GITHUB_NAME:-}");
    }
    if (config.integrations.gitlab) {
      lines.push("      - GITLAB_TOKEN=${GITLAB_TOKEN:-}");
      lines.push("      - GITLAB_EMAIL=${GITLAB_EMAIL:-}");
    }
    if (config.integrations.sentry) {
      lines.push("      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN:-}");
      lines.push("      - SENTRY_ORG=${SENTRY_ORG:-}");
    }

    lines.push("");
    lines.push("    ports:");
    lines.push(`      - "${svc.port}:3000"`);
    lines.push("");
    lines.push("    volumes:");
    lines.push("      - swarm_logs:/logs");
    lines.push("      - swarm_shared:/workspace/shared");
    lines.push(`      - ${svc.volumeName}:/workspace/personal`);
    lines.push("");
    lines.push("    restart: unless-stopped");
  }

  // Volumes
  lines.push("");
  lines.push("volumes:");
  lines.push("  swarm_api:");
  lines.push("  swarm_logs:");
  lines.push("  swarm_shared:");
  for (const svc of services) {
    lines.push(`  ${svc.volumeName}:`);
  }

  return lines.join("\n") + "\n";
}

export function generateEnv(config: ComposeConfig): string {
  resetUUIDCounter();
  const services = buildServices(config);
  const lines: string[] = [];

  lines.push("# Agent Swarm Environment Configuration");
  lines.push("# Generated by Agent Swarm Templates Builder");
  lines.push("");
  lines.push("# API Configuration");
  lines.push("API_KEY=your-api-key-here");
  lines.push("MCP_BASE_URL=http://localhost:3013");
  lines.push("APP_URL=http://localhost:5274");
  lines.push("");
  lines.push("# Claude Authentication");
  lines.push("CLAUDE_CODE_OAUTH_TOKEN=your-oauth-token-here");
  lines.push("");
  lines.push("# Swarm URL (for external access)");
  lines.push("SWARM_URL=localhost");

  if (config.integrations.slack) {
    lines.push("");
    lines.push("# Slack Integration");
    lines.push("SLACK_DISABLE=false");
    lines.push("SLACK_BOT_TOKEN=xoxb-your-bot-token");
    lines.push("SLACK_APP_TOKEN=xapp-your-app-token");
  }

  if (config.integrations.github) {
    lines.push("");
    lines.push("# GitHub Integration");
    lines.push("GITHUB_TOKEN=ghp_your-token");
    lines.push("GITHUB_EMAIL=your-email@example.com");
    lines.push("GITHUB_NAME=Your Name");
  }

  if (config.integrations.gitlab) {
    lines.push("");
    lines.push("# GitLab Integration");
    lines.push("GITLAB_TOKEN=glpat-your-token");
    lines.push("GITLAB_EMAIL=your-email@example.com");
  }

  if (config.integrations.sentry) {
    lines.push("");
    lines.push("# Sentry Integration");
    lines.push("SENTRY_AUTH_TOKEN=your-sentry-token");
    lines.push("SENTRY_ORG=your-org");
  }

  lines.push("");
  lines.push("# Agent IDs (auto-generated UUIDs, keep stable for task resume)");
  for (const svc of services) {
    lines.push(`# ${svc.name}: ${svc.agentId}`);
  }

  return lines.join("\n") + "\n";
}
